services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  backend:
    build:
      context: ./analytics-backend
    volumes:
      - ./analytics-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./analytics-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
